version: '3'
services:

    bootstrap:
      build: .
      command: ["-b"]
      networks:
        app_net:
          ipv4_address: 172.16.238.10
      stdin_open: true
      tty: true

    peer:
      build: .
      command: ["-p", "172.16.238.10"]
      depends_on:
        - "bootstrap"
      networks: 
        - app_net
      stdin_open: true
      tty: true


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24


